FILENAME: C:\Users\Administrator\Documents\UNESCO\monecolenligne.cm\Eric - 20210406\LISTE DES ELEVES DE L'ECOLE GEPPS CITE SIC\LISTE DES ELEVES DE L'ECOLE GEPPS CITE SIC.xlsx
SAVE_PATH: C:\Users\Administrator\Documents\UNESCO\monecolenligne.cm\Eric - 20210406\LISTE DES ELEVES DE L'ECOLE GEPPS CITE SIC
UPDATE_USERNAME: True
UPDATE_NAMES: True
UPDATE_PASSWORD: True
EXPORT_CSV: True
CSV_DELIMITER: ";"