FILENAME: E:\UNESCO\monecolenligne.cm\Eric - 20210406\11. LISTE DES ELEVES GBPS BONAMOUSSADI 2 FRANCO\LISTE DES ELEVES GBPS BONAMOUSSADI 2 FRANCO.xlsx
SAVE_PATH: E:\UNESCO\monecolenligne.cm\Eric - 20210406\11. LISTE DES ELEVES GBPS BONAMOUSSADI 2 FRANCO
UPDATE_USERNAME: True
UPDATE_NAMES: True
UPDATE_PASSWORD: True
EXPORT_CSV: True
CSV_DELIMITER: ";"
PASSWORD_LENGTH: 3

